# Generated by Django 4.1.1 on 2022-11-02 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no name')),
                ('que', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no name')),
                ('fname', models.TextField(default='no fname')),
                ('lname', models.CharField(default='no lname', max_length=100)),
                ('email', models.EmailField(default='no email', max_length=254)),
                ('phone', models.TextField(default=-1, max_length=10)),
                ('gender', models.CharField(default='U', max_length=1)),
                ('score', models.IntegerField(default=-1)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
